import { MatchType, PrimitiveType, Type } from './types';
export declare const INT_TY: PrimitiveType;
export declare const REAL_TY: PrimitiveType;
export declare const STR_TY: PrimitiveType;
export declare const CHAR_TY: PrimitiveType;
export declare const BOOL_TY: PrimitiveType;
export declare const UNIT_TY: PrimitiveType;
export declare function isInt(type: Type): boolean;
export declare function isReal(type: Type): boolean;
export declare function isStr(type: Type): boolean;
export declare function isChar(type: Type): boolean;
export declare function isBool(type: Type): boolean;
export declare function isUnit(type: Type): boolean;
export declare function isPrimitiveType(type: Type): type is PrimitiveType;
export declare function isMatchType(type: Type): type is MatchType;
export declare function isSameType(fst: Type, snd: Type): boolean;
export declare function makeMatchType(...types: Type[]): MatchType;
export declare function curryMatchTypes(paramTypes: Type[], returnType: Type): MatchType;
export declare function stringifyType(type: Type | Type[]): string;
